deployfolder/objects/Account_Fax__c.object
<CustomObject>
    <label>Account Fax</label>
    <nameField>
        <displayFormat>AFI-{000000}</displayFormat>
        <label>Account Fax ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Fax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Application_ID__c</fullName>
        <description>used to capture Application ID from ISP and referred by ETL workflow to avoid generating duplicate records in salesforce</description>
        <label>Application ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_ID__c</fullName>
        <label>Corp ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>ISP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>De-activated</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Rebilling Failed</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delinquent</fullName>
                </value>
                <value>
                    <fullName>Re-opened</fullName>
                </value>
                <value>
                    <fullName>Suspended - KIS</fullName>
                </value>
                <value>
                    <fullName>Sent to Collection</fullName>
                </value>
                <value>
                    <fullName>Provisioned</fullName>
                </value>
                <value>
                    <fullName>Inactive (Dead)</fullName>
                </value>
                <value>
                    <fullName>Inactive (Winback)</fullName>
                </value>
                <value>
                    <fullName>Partner (Prospect)</fullName>
                </value>
                <value>
                    <fullName>Partner (Active)</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

deployfolder/classes/Test_Batch_ETLUpdate.cls
@isTest
public class Test_Batch_ETLUpdate {

    @testSetup static void setup() {
       
        Account_Fax__c ax = new Account_Fax__c();
        ax.Application_Id__c = 'A19028';
        ax.Status__c = 'Active';
        insert ax;
        
        Account acc = new Account();
        acc.name = 'Batch Account';
        insert acc;  
    } 
    @isTest
    public static void method1() {
        Test.startTest();
        Database.executeBatch(new Batch_ETLUpdate());
        Test.stopTest(); 
    }
    @isTest
    public static void method2() {
        Account acc = [Select id,name,Application_ID__c from Account Limit 1];
        Account_Fax__c ax = [Select id,Application_Id__c,Status__c from Account_Fax__c Limit 1];
        acc.Application_ID__c = ax.Application_ID__c;
        update acc;
        Test.startTest();
        Database.executeBatch(new Batch_ETLUpdate());
        Test.stopTest(); 
    }
    @isTest
    public static void method3() {
        Account_Fax__c ax = [Select id,Application_Id__c,Status__c from Account_Fax__c Limit 1];
        ax.Corp_ID__c = '0000';
        Account acc = [Select id,name,Application_ID__c from Account Limit 1];
        acc.Application_ID__c = ax.Application_ID__c;
        acc.Corp_ID__c ='0001';
        update ax;
        update acc;
        Test.startTest();
        Database.executeBatch(new Batch_ETLUpdate());
        Test.stopTest(); 
    }
    @isTest
    public static void testschedule() {
		Test.StartTest();
		Batch_ETLUpdateScheduler upSch = new Batch_ETLUpdateScheduler();
		system.schedule('Test status Check', '0 0 23 * * ?', upSch );
		Test.stopTest();
	}
    
}