deployfolder/objects/Account_Fax__c.object
<CustomObject>
    <label>Account Fax</label>
    <nameField>
        <displayFormat>AFI-{000000}</displayFormat>
        <label>Account Fax ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounts Fax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Accounts_Payable__c</fullName>
        <label>Accounts Payable</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>PAID</fullName>
                </value>
                <value>
                    <fullName>Free</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Lead - A</fullName>
                </value>
                <value>
                    <fullName>Lead - B</fullName>
                </value>
                <value>
                    <fullName>Lead - C</fullName>
                </value>
                <value>
                    <fullName>CRM - Signed Customer</fullName>
                </value>
                <value>
                    <fullName>CPA - Signed Customer Pending Cancellation</fullName>
                </value>
                <value>
                    <fullName>CRM - Signed Customer in Implementation</fullName>
                </value>
                <value>
                    <fullName>CRM - Cancelled</fullName>
                </value>
                <value>
                    <fullName>CRM - Cancelled - Non Payment</fullName>
                </value>
                <value>
                    <fullName>Campaigner - Active</fullName>
                </value>
                <value>
                    <fullName>Campaigner - Suspended</fullName>
                </value>
                <value>
                    <fullName>Campaigner - Cancelled</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Partner &amp; Customer</fullName>
                </value>
                <value>
                    <fullName>Partner Prospect</fullName>
                </value>
                <value>
                    <fullName>Pilot Customer</fullName>
                </value>
                <value>
                    <fullName>CSPM Customer (Playbook)</fullName>
                </value>
                <value>
                    <fullName>Partner - Nurture</fullName>
                </value>
                <value>
                    <fullName>Partner - Cancel</fullName>
                </value>
                <value>
                    <fullName>Partner - Active</fullName>
                </value>
                <value>
                    <fullName>Contactology</fullName>
                </value>
                <value>
                    <fullName>JBlast</fullName>
                </value>
                <value>
                    <fullName>EmailDirect</fullName>
                </value>
                <value>
                    <fullName>Publicaster</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Acct_End_Date__c</fullName>
        <label>Account End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Acct_Start_Date__c</fullName>
        <label>Account Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Address_Line_3__c</fullName>
        <label>Address Line 3</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Admin__c</fullName>
        <label>Admin</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_ID__c</fullName>
        <description>used to capture Application ID from ISP and referred by ETL workflow to avoid generating duplicate records in salesforce</description>
        <label>Application ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCity__c</fullName>
        <label>BillingCity</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCountry__c</fullName>
        <label>BillingCountry</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingPostalCode__c</fullName>
        <label>BillingPostalCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingStreet__c</fullName>
        <label>BillingStreet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Please enter the j2 Global Inc. Brand</description>
        <inlineHelpText>Please enter the j2 Global Inc. Brand</inlineHelpText>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>eFax Developer</fullName>
                </value>
                <value>
                    <fullName>Fax.com</fullName>
                </value>
                <value>
                    <fullName>RapidFAX</fullName>
                </value>
                <value>
                    <fullName>Send2Fax</fullName>
                </value>
                <value>
                    <fullName>Smartfax</fullName>
                </value>
                <value>
                    <fullName>Trustfax</fullName>
                </value>
                <value>
                    <fullName>jConnect</fullName>
                </value>
                <value>
                    <fullName>eFax</fullName>
                </value>
                <value>
                    <fullName>eVoice</fullName>
                </value>
                <value>
                    <fullName>eFax Corporate</fullName>
                </value>
                <value>
                    <fullName>Electric Mail</fullName>
                </value>
                <value>
                    <fullName>Venali</fullName>
                </value>
                <value>
                    <fullName>FuseMail</fullName>
                </value>
                <value>
                    <fullName>MailWise</fullName>
                </value>
                <value>
                    <fullName>Enterprise Mailer</fullName>
                </value>
                <value>
                    <fullName>M4 Internet</fullName>
                </value>
                <value>
                    <fullName>Quexion</fullName>
                </value>
                <value>
                    <fullName>MyFax</fullName>
                </value>
                <value>
                    <fullName>KeepItSafe</fullName>
                </value>
                <value>
                    <fullName>Landslide</fullName>
                </value>
                <value>
                    <fullName>OneBox</fullName>
                </value>
                <value>
                    <fullName>MetroFax</fullName>
                </value>
                <value>
                    <fullName>Sfax</fullName>
                </value>
                <value>
                    <fullName>Infonet</fullName>
                </value>
                <value>
                    <fullName>JBlast</fullName>
                </value>
                <value>
                    <fullName>Protus IP Solutions</fullName>
                </value>
                <value>
                    <fullName>Rogers Business Internet Fax</fullName>
                </value>
                <value>
                    <fullName>Telus</fullName>
                </value>
                <value>
                    <fullName>Virtual Fax</fullName>
                </value>
                <value>
                    <fullName>Campaigner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Closed_On__c</fullName>
        <label>Closed On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Closed_Reason__c</fullName>
        <label>Closed Reason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Collection_Method__c</fullName>
        <label>Collection Method</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Corp_ID__c</fullName>
        <label>Corp ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <inlineHelpText>LiveVault NetSuite Customer ID</inlineHelpText>
        <label>Customer ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reseller_ID__c</fullName>
        <label>Reseller ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reseller_Name__c</fullName>
        <label>Reseller Name</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Group__c</fullName>
        <description>Field Value under Consideration for differentiating the Sales Groups - CORP Sales; INSIDE Sales; OUTBOUND Sales</description>
        <inlineHelpText>Field Value under Consideration for differentiating the Sales Groups - CORP Sales; INSIDE Sales; OUTBOUND Sales</inlineHelpText>
        <label>Sales Group</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep__c</fullName>
        <label>Sales Rep</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secure__c</fullName>
        <label>Secure</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System_Notes__c</fullName>
        <label>Source System Notes</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Description__c</fullName>
        <label>Status Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>ISP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Trial</fullName>
                </value>
                <value>
                    <fullName>De-activated</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
                <value>
                    <fullName>Rebilling Failed</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Delinquent</fullName>
                </value>
                <value>
                    <fullName>Re-opened</fullName>
                </value>
                <value>
                    <fullName>Suspended - KIS</fullName>
                </value>
                <value>
                    <fullName>Sent to Collection</fullName>
                </value>
                <value>
                    <fullName>Provisioned</fullName>
                </value>
                <value>
                    <fullName>Inactive (Dead)</fullName>
                </value>
                <value>
                    <fullName>Inactive (Winback)</fullName>
                </value>
                <value>
                    <fullName>Partner (Prospect)</fullName>
                </value>
                <value>
                    <fullName>Partner (Active)</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Qualified</fullName>
                </value>
                <value>
                    <fullName>Pending Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Update_Status__c</fullName>
        <label>Update Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/Batch_ETLUpdate.cls
global class Batch_ETLUpdate implements Database.Batchable<SObject>,Database.Stateful{
    public List<Account> acToUpdate;
    public List<Account_Fax__c> accFaxList;
    global List<String> exception_List;
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query='';
        String status = 'Completed';
        query = 'SELECT Id,Acct_End_Date__c,Acct_Start_Date__c,Account_Type__c,Accounts_Payable__c,Address_Line_3__c,'+
                  		'Admin__c,Application_Id__c,BillingCity__c,BillingCountry__c,BillingPostalCode__c,BillingStreet__c,Brand__c,Closed_On__c,'+
                        'Closed_Reason__c,Collection_Method__c,Currency__c,Customer_ID__c,Reseller_ID__c,Sales_Group__c,'+
                        'Reseller_Name__c,Sales_Rep__c,Secure__c,Source_System_Notes__c,Corp_ID__c,Status__c,Update_Status__c'+
                ' FROM Account_Fax__c WHERE Update_Status__c!=:status';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account_Fax__c> scope){
        
        accFaxList = new List<Account_Fax__c>();
        acToUpdate = new List<Account>();
        for(Account_Fax__c ax:scope){
            if(ax.Application_Id__c == Null || ax.Application_ID__c == ''){
                ax.Status_Description__c = 'Application Id is Blank';
                ax.Update_Status__c = 'Failed';
                accFaxList.add(ax);
            }else{
            List<Account> actList2 = [SELECT Id,Acct_End_Date__c,Acct_Start_Date__c,Account_Type__c,Accounts_Payable__c,Address_Line_3__c,
                                      Admin__c,BillingCity__c,Application_Id__c,BillingCountry__c,
                                      Brand__c,Closed_On__c,Closed_Reason__c,Collection_Method__c,Currency__c,Customer_ID__c,Reseller_ID__c,
                                      Sales_Group__c,Reseller_Name__c,Sales_Rep__c,Secure__c,Source_System_Notes__c,Corp_ID__c,Status__c
                                      FROM Account WHERE Application_Id__c !=null AND Application_Id__c =: ax.Application_Id__c];
            
            if(actList2.size() == 0 || (actList2.size() == NULL && actList2.isEmpty())){
                ax.Status_Description__c = 'No match is found';
                ax.Update_Status__c = 'Failed';
                accFaxList.add(ax);
            }
            else if(actList2.size() > 1){
                ax.Status_Description__c = 'Duplicate records found (more than one account having same application ID)';
                ax.Update_Status__c = 'Failed';
                accFaxList.add(ax);
            }
            else if(actList2.size() == 1){
                if(actList2[0].Corp_ID__c != NULL && ax.Corp_ID__c != NULL && ax.Corp_ID__c != actList2[0].Corp_ID__c){
                    ax.Status_Description__c = 'CORP ID Mismatch';
                    ax.Update_Status__c = 'Failed';
                    accFaxList.add(ax);
                }else{
                    try{
                        if(ax.Acct_End_Date__c!=null) actList2[0].Acct_End_Date__c = ax.Acct_End_Date__c;
                        if(ax.Acct_Start_Date__c!=null) actList2[0].Acct_Start_Date__c = ax.Acct_Start_Date__c;
                        if(ax.Account_Type__c!=null) actList2[0].Account_Type__c = ax.Account_Type__c;
                        if(ax.Accounts_Payable__c!=null) actList2[0].Accounts_Payable__c = ax.Accounts_Payable__c;
                        if(ax.Address_Line_3__c!=null) actList2[0].Address_Line_3__c = ax.Address_Line_3__c;
                        if(ax.Admin__c!=null) actList2[0].Admin__c = ax.Admin__c;
                        if(ax.BillingCity__c!=null) actList2[0].BillingCity__c = ax.BillingCity__c;
                        if(ax.BillingCountry__c!=null) actList2[0].BillingCountry__c = ax.BillingCountry__c;
                        if(ax.BillingPostalCode__c!=null) actList2[0].BillingPostalCode__c = ax.BillingPostalCode__c;
                        if(ax.BillingStreet__c!=null) actList2[0].BillingStreet__c = ax.BillingStreet__c;
                        if(ax.Brand__c!=null) actList2[0].Brand__c = ax.Brand__c;
                        if(ax.Closed_On__c!=null) actList2[0].Closed_On__c = ax.Closed_On__c;
                        if(ax.Closed_Reason__c!=null) actList2[0].Closed_Reason__c = ax.Closed_Reason__c;
                        if(ax.Collection_Method__c!=null) actList2[0].Collection_Method__c = ax.Collection_Method__c;
                        if(ax.Corp_ID__c!=null)	actList2[0].Corp_ID__c = ax.Corp_ID__c;
                        if(ax.Currency__c!=null) actList2[0].Currency__c = ax.Currency__c;
                        if(ax.Customer_ID__c!=null)	actList2[0].Customer_ID__c = ax.Customer_ID__c;
                        if(ax.Reseller_ID__c!=null)	actList2[0].Reseller_ID__c = ax.Reseller_ID__c;
                        if(ax.Sales_Group__c!=null)	actList2[0].Sales_Group__c = ax.Sales_Group__c;
                        if(ax.Reseller_Name__c!=null) actList2[0].Reseller_Name__c = ax.Reseller_Name__c;
                        if(ax.Sales_Rep__c!=null) actList2[0].Sales_Rep__c = ax.Sales_Rep__c;
                        if(ax.Secure__c!=null) actList2[0].Secure__c = ax.Secure__c;
                        if(ax.Source_System_Notes__c!=null)	actList2[0].Source_System_Notes__c = ax.Source_System_Notes__c;
                        if(ax.Status__c!=null) actList2[0].Status__c = ax.Status__c;
                        acToUpdate.add(actList2[0]);
                        ax.Status_Description__c = 'Update successful';
                        ax.Update_Status__c = 'Completed';
                        accFaxList.add(ax);
                    }catch(Exception ex){
                        ax.Status_Description__c = 'The account is facing validation error/process error. kindly review the account record->'+ax.Id;
                        ax.Update_Status__c = 'Failed';
                        accFaxList.add(ax);
                    }
                }
            }
            }
        }
        
        if(acToUpdate!=NULL && !acToUpdate.isEmpty()){
            update acToUpdate;
        }
        
        if(!accFaxList.isEmpty()){
            Database.SaveResult[] updateResults = Database.update(accFaxList, false);
            List<Account_Fax__c> afaxList = new List<Account_Fax__c>();
            for(Integer i=0;i<updateResults.size();i++){
                if(!updateResults.get(i).isSuccess()){
                    Database.Error errors =  updateResults.get(i).getErrors().get(0);
                    Account_Fax__c afax = new Account_Fax__c();
                    afax.Update_Status__c = 'Failed';
                    afax.Status_Description__c = 'The account is facing validation error/process error. kindly review the account record->';
                    afaxList.add(afax);
                }                
            }
            if(afaxList.size()>0) update afaxList;
        }
        
    }
    global void finish(Database.BatchableContext BC){}
}