deployfolder/objects/Consensus__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Consensus</label>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank__c</fullName>
        <label>Bank</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>eFax__c</fullName>
        <label>eFax</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>J2TaxID__c</fullName>
        <label>J2TaxID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>J2_Address__c</fullName>
        <label>J2 Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>J2_State__c</fullName>
        <label>J2 State</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>J2_Street__c</fullName>
        <label>J2 Street</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing__c</fullName>
        <label>Routing #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Swift_Code__c</fullName>
        <label>Swift Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone__c</fullName>
        <label>Telephone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

deployfolder/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Billing_Run_Date__c</fullName>
        <description>KIS - Invoicing - Use this Date field to specify the Invoicing Run Date - in place of system date - This allows KeepItSafe to run billing for the month in advance of the 1st of the month.</description>
        <inlineHelpText>KIS - Invoicing - Use this Date field to specify the Invoicing Run Date - in place of system date - This allows KeepItSafe to run billing for the month in advance of the 1st of the month. (MM/DD/YYYY)</inlineHelpText>
        <label>Billing Run Date *Verify Date Format</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consensus_Amount_Breakdown__c</fullName>
        <description>Consensus Amount Breakdown</description>
        <label>Consensus Amount Breakdown</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consensus_Price__c</fullName>
        <description>Consensus Price</description>
        <label>Consensus Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Consensus_Quantity__c</fullName>
        <description>Consensus Quantity</description>
        <label>Consensus Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description_Period__c</fullName>
        <description>KIS BIlling - Suppress True = Account Name + Appends Month YYYY + adds the Custom Invoice Description value  or Suppress False = Standard Description + Appends Month YYYY + adds the Custom Invoice Description value</description>
        <formula>IF(Account__r.ParentId &lt;&gt; null &amp;&amp; Audit_Send_Bill_To__c==&apos;Partner&apos;,

Account__r.Name + &quot; - &quot; + DescMonth__c + &quot; &quot; + DescYear__c + &quot; - &quot; + Custom_Invoice_Description__c + &quot; - &quot; + TEXT(Usage_GB__c) + &quot; GB&quot;+&quot; - &quot; + PO__c,

Account__r.Name + &quot; - &quot; + DescMonth__c + &quot; &quot; + DescYear__c + &quot; - &quot; + Custom_Invoice_Description__c+&quot; - &quot; + PO__c

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>KIS BIlling - Suppress True = Account Name + Appends Month YYYY + adds the Custom Invoice Description value  or Suppress False = Standard Description + Appends Month YYYY + adds the Custom Invoice Description value</inlineHelpText>
        <label>Invoice Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number1__c</fullName>
        <description>created to capture line number info for Consensus and KIS NL</description>
        <label>Line Number1</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity lookup for consensus</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>ConsensusOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <formula>TEXT (Account__r.Payment_Method__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <formula>Account__r.Payment_Terms__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Terms</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/ConsensusController.cls
public class ConsensusController {
    public string J2Address {get;set;}
    public string J2State {get;set;}
    public string J2Street {get;set;}
    public string J2AccountName {get;set;}
    public string J2AccontNumber {get;set;}
    public string J2Routing {get;set;}
    public String J2SwiftCode {get;set;}
    public string J2Bank {get;set;}
    public string Telephone {get;set;}
    public string eFax {get;set;}
    public string j2TAXID {get;set;}
    public string dueDate {get;set;}
    public Opportunity oppData;
    public Contact con {get;set;}
    public List<Invoice__c> consensusInvoice {get;set;}
    public Decimal totalDueAmount {get;set;}
    public string orgCurrency {get;set;}
    public Boolean InvoiceFooter {get;set;}
    public Boolean CreditCardFooter {get;set;}
    
    public ConsensusController(Apexpages.StandardController controller) {
        Opportunity opp = (Opportunity)controller.getRecord();
        if(opp != null) {
            //get the invoice Data
            consensusInvoice = [SELECT id, Consensus_Amount_Breakdown__c, 
                                Consensus_Price__c, Consensus_Quantity__c, 
                                Description_Period__c, Status__c  
                                FROM Invoice__c 
                                WHERE Opportunity__c = :opp.Id AND Status__c = 'Active' AND Billing_Run_Date__c = THIS_MONTH ORDER BY Line_Number1__c];
            getTotalCharges();
            oppData = [SELECT Id, AccountId, Account.Corp_ID__c, Account.Payment_Method__c, Consensus_Invoice_No__c, Account.Sales_Rep__c, Account.Payment_Terms__c,Account.Payment_Terms_New__c from Opportunity where id =:opp.Id];   
        }
        if(oppData != null) {
            try{
                //get the contact information from account Id
                con = [SELECT Id,Name from Contact where accountId = : oppData.AccountId LIMIT 1];   
            }catch(Exception ex) {}
        }
        getcallCustomSetting();
        getDueDate();
        InvoicePaymentMethod();
        CreditCardPaymentMethod();
    }
    /*
* Fetching all the static values related to this invoice 
* from Custom setting
*/
    public void getcallCustomSetting() {
        Consensus__c test = Consensus__c.getvalues('J2Address');
        J2Address = test.J2_Address__c;
        J2Street = test.J2_Street__c;
        J2State = test.J2_State__c;
        J2AccountName = test.Account_Name__c;
        J2AccontNumber = test.Account_Number__c;
        J2Routing = test.Routing__c;
        J2SwiftCode = test.Swift_Code__c;
        J2Bank = test.Bank__c;
        Telephone = test.Telephone__c;
        eFax = test.eFax__c;
        j2TAXID = test.J2TaxID__c;
    }
    
    public void getDueDate() {
        Date monthEndDate = Date.today().toStartofMonth().addMonths(1).addDays(-1);
        dueDate = DateTime.newInstance(monthEndDate.year(),monthEndDate.month(),monthEndDate.day()).format('MM-d-YYYY');
    }
    
    public void getTotalCharges() {
        orgCurrency = UserInfo.getDefaultCurrency();
        totalDueAmount = 0.00;
        if(consensusInvoice != null) {
            for(Invoice__c invCharges : consensusInvoice) {
                totalDueAmount =  totalDueAmount + invCharges.Consensus_Amount_Breakdown__c;            
            }
        }
    }
    
    public Boolean InvoicePaymentMethod() {
        InvoiceFooter =false;
        if(oppData.Account.Payment_Method__c == 'Invoice') {
            InvoiceFooter = true;
        }
        return InvoiceFooter;
    }
    
    public Boolean CreditCardPaymentMethod() {
        CreditCardFooter =false;
        if(oppData.Account.Payment_Method__c == 'Credit Card') {
            CreditCardFooter = true;
        }
        return CreditCardFooter;
    }
}