deployfolder/objects/FortuneRankDatabase__mdt.object
<CustomObject>
    <description>This metadata is used to store the information about the fortune rank</description>
    <label>FortuneRankDatabase</label>
    <pluralLabel>FortuneRankDatabases</pluralLabel>
    <fields>
        <fullName>ComponyName__c</fullName>
        <description>Used to store the Company name for Fortune Rank</description>
        <inlineHelpText>Used to store the Company name for Fortune Rank</inlineHelpText>
        <label>CompanyName</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <description>Used to store the information about Domain for fortune Rank.</description>
        <inlineHelpText>Used to store the information about Domain for fortune Rank.</inlineHelpText>
        <label>Domain</label>
        <length>250</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/fortuneRanktestclass.cls
@isTest
public class fortuneRanktestclass {
    private static testmethod void myunittest(){
        Lead le= new Lead();
        Le.LastName='john smith';
        Le.Email='xyz@amazon.com';
        Le.Company='Amazon';
        Le.Status='Converted';
        Le.LeadSource='Direct';
        insert Le;
        
        FortuneRankDatabase__mdt fmd= new FortuneRankDatabase__mdt();
        fmd.Label='Amazon';
        fmd.DeveloperName='Amazon';
        fmd.ComponyName__c='amazon';
        fmd.Domain__c='amazon.com';
       
    }
}