deployfolder/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sign_Up_Date__c</fullName>
        <label>Sign Up Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

deployfolder/classes/InvoiceInactiveSchedularTest.cls
@isTest
public class InvoiceInactiveSchedularTest{
    
    public static String CRON_EXP = '0 0 0 3 9 ? 2022';
    
    public static  testmethod void InvoiceSchedularTest(){
    
        Account a = new Account();
        a.Name = 'Test Account';
        a.Deactivate_Invoice__c = true;
        insert a;
        
       Invoice__c i = new Invoice__c();
       i.Account__c = a.Id;
       i.Sign_Up_Date__c = system.today();
       i.Status__c = 'Active';
       insert i;
       
       InvoiceInactiveSchedular inv= new InvoiceInactiveSchedular ();
       
       
       
       String jobId = System.schedule('testSchedular',CRON_EXP, inv);
    }
}