deployfolder/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <description>Oracle Billing uses this value to define the calculation and splits of Deferred Revenue, in case of a -ive Amount value, this value should be Blank</description>
        <inlineHelpText>Oracle Billing uses this value to define the calculation and splits of Deferred Revenue, in case of a -ive Amount value, this value should be Blank</inlineHelpText>
        <label>Billing Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Bi-Annual</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>One-off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Reason__c</fullName>
        <label>Invoice Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition</fullName>
                </value>
                <value>
                    <fullName>Cheaper Solution/Cost Cutting</fullName>
                </value>
                <value>
                    <fullName>Closed Down</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Delinquent</fullName>
                </value>
                <value>
                    <fullName>Dis-satisfied with Service</fullName>
                </value>
                <value>
                    <fullName>Lost Through Re-seller</fullName>
                </value>
                <value>
                    <fullName>Merger/Alliance</fullName>
                </value>
                <value>
                    <fullName>Moved to Cloud Solution</fullName>
                </value>
                <value>
                    <fullName>Moved to Bulk Invoice</fullName>
                </value>
                <value>
                    <fullName>New Contract in Place</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sign_Up_Date__c</fullName>
        <label>Sign Up Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
</CustomObject>

deployfolder/classes/OracleInvoiceID.cls
Public Class OracleInvoiceID {
@istest    
    public static void OracleInvoiceID()     
    {        
        Account a = new Account();
        a.Name = 'Test Account';
        insert a;
        
        
        
        Invoice__c i = new Invoice__c(                                     
            Billing_Period__c = 'Annual',                                    
            Account__c = a.Id,                                                                        
            Amount__c = 100.52,                                                       
            Sign_Up_Date__c = system.TODAY(),
            Invoice_Reason__c = 'Closed Down');   
                                                                    
    insert i;   
    update i;                     
    }
   }