deployfolder/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Period__c</fullName>
        <description>Oracle Billing uses this value to define the calculation and splits of Deferred Revenue, in case of a -ive Amount value, this value should be Blank</description>
        <inlineHelpText>Oracle Billing uses this value to define the calculation and splits of Deferred Revenue, in case of a -ive Amount value, this value should be Blank</inlineHelpText>
        <label>Billing Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Bi-Annual</fullName>
                </value>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>One-off</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sign_Up_Date__c</fullName>
        <label>Sign Up Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
</CustomObject>

deployfolder/classes/AnnualInvoice.cls
@isTest
private Class AnnualInvoice {
    
    @isTest static void AnnualInvoice()
         {
             // record typ is set to KIS NL -> 012320000005P4IAAU
            Account accParentKIS = new Account(Name='TestAccount', RecordTypeId='012320000005P4IAAU', Support_Level__c ='Regular');
            insert accParentKIS;
            Account tempParentKIS = [SELECT Id, Sales_Owner__c, Support_Level__c FROM Account WHERE Name='TestAccount'];
           
            Invoice__c a = new Invoice__c( 
                                        Billing_Period__c = 'Annual',
                                        Account__c = tempParentKIS.Id,                                    
                                        Amount__c = 100.52,                    
                                        Sign_Up_Date__c = system.TODAY());                                                        
       insert a;
       update a;                 
        }
    }