deployfolder/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>April__c</fullName>
        <label>April</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August__c</fullName>
        <label>August</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Run_Date__c</fullName>
        <description>KIS - Invoicing - Use this Date field to specify the Invoicing Run Date - in place of system date - This allows KeepItSafe to run billing for the month in advance of the 1st of the month.</description>
        <inlineHelpText>KIS - Invoicing - Use this Date field to specify the Invoicing Run Date - in place of system date - This allows KeepItSafe to run billing for the month in advance of the 1st of the month. (MM/DD/YYYY)</inlineHelpText>
        <label>Billing Run Date *Verify Date Format</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>December__c</fullName>
        <label>December</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February__c</fullName>
        <label>February</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>January__c</fullName>
        <label>January</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July__c</fullName>
        <label>July</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June__c</fullName>
        <label>June</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March__c</fullName>
        <label>March</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May__c</fullName>
        <label>May</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November__c</fullName>
        <label>November</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October__c</fullName>
        <label>October</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>September__c</fullName>
        <label>September</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/Scheduled_Invoice_Update.cls
global class Scheduled_Invoice_Update implements Schedulable 
{
  global void execute(SchedulableContext ctx) 
  {
    // Map for selecting the next month to check the billing
    Map<Integer,String> nextMonthFieldMap = new Map<Integer,String>();
    nextMonthFieldMap.put(1,'February__c');
    nextMonthFieldMap.put(2,'March__c');
    nextMonthFieldMap.put(3,'April__c');
    nextMonthFieldMap.put(4,'May__c');
    nextMonthFieldMap.put(5,'June__c');
    nextMonthFieldMap.put(6,'July__c');
    nextMonthFieldMap.put(7,'August__c');
    nextMonthFieldMap.put(8,'September__c');
    nextMonthFieldMap.put(9,'October__c');
    nextMonthFieldMap.put(10,'November__c');
    nextMonthFieldMap.put(11,'December__c');
    nextMonthFieldMap.put(12,'January__c');


    /* 
    TO DO : 
      - Verify that if month is december we look for January's billing value
    */


    // Select all the Invoices that have the next month's billing > 0
    List<Invoice__c> invoicesToUpdateBillingRunDate = new List<Invoice__c>();

    Integer currentMonthNumber = Date.Today().Month();
    String nextMonth = nextMonthFieldMap.get(currentMonthNumber);

    // Prepare SOQL Querry for Active invoices with Billing due in next month
    String soqlQuery = 'SELECT Id, Billing_Run_Date__c, Status__c, ' + nextMonth + ' FROM Invoice__c WHERE Status__c=\'Active\' AND ' + nextMonth + ' > 0';

    invoicesToUpdateBillingRunDate = database.query(soqlQuery);

    // Update Billing Run Date field 
    for(Invoice__c inv : invoicesToUpdateBillingRunDate)
    {

      Date today = date.Today();
      Date new_Billing_Run_Date = today.addMonths(1);
      new_Billing_Run_Date = new_Billing_Run_Date.toStartOfMonth();
      inv.Billing_Run_Date__c = new_Billing_Run_Date;

    }

    update invoicesToUpdateBillingRunDate;
  }
}