deployfolder/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Reason__c</fullName>
        <label>Invoice Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acquisition</fullName>
                </value>
                <value>
                    <fullName>Cheaper Solution/Cost Cutting</fullName>
                </value>
                <value>
                    <fullName>Closed Down</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Delinquent</fullName>
                </value>
                <value>
                    <fullName>Dis-satisfied with Service</fullName>
                </value>
                <value>
                    <fullName>Lost Through Re-seller</fullName>
                </value>
                <value>
                    <fullName>Merger/Alliance</fullName>
                </value>
                <value>
                    <fullName>Moved to Cloud Solution</fullName>
                </value>
                <value>
                    <fullName>Moved to Bulk Invoice</fullName>
                </value>
                <value>
                    <fullName>New Contract in Place</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Suspended</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

deployfolder/classes/j2_KeepitSafe_InvoiceUpdateClass.cls
public with sharing class j2_KeepitSafe_InvoiceUpdateClass {
    
    public void invoiceUpdate(Map<Id, Account> accMap){
        
        List<Invoice__c> Invlist = [SELECT Id, Status__c, Account__c,Account__r.Reason__c,Invoice_Reason__c
                                    FROM Invoice__c 
                                    WHERE Account__c IN: accMap.keyset()];
        
        list<Invoice__c> UpdateInv = new list<Invoice__c>();
        
        if(Invlist.size() > 0) {
            for(Invoice__c i: Invlist){
                i.Status__c = 'Inactive';
                i.invoice_Reason__c = i.Account__r.Reason__c;
                UpdateInv.add(i);
            }
        }
        if(UpdateInv.size() > 0) {
            update UpdateInv;    
        }
    }
}